{
    "name": "Purchase Advance Payment",
    "version": "14.0.4.13062025",
    "author": "PT Industrial Multi Fan",
    "maintainer": "aRai",
    "website": "https://kipascke.co.id",
    "category": "Purchase",
    "license": "AGPL-3",
    "summary": "Allow to add advance payments on purchase orders",
    "depends": ["purchase", "cke_vendor_child"],
    "data": [
        "wizard/purchase_advance_payment_wizard_view.xml",
        "wizard/vendor_bill_advance_payment_wizard_view.xml",
        "views/account_move_tree_view.xml",
        "views/purchase_view.xml",
        "views/account_move_commercial_invoice_view.xml",
        "views/account_move_payment_advances.xml",
        "security/ir.model.access.csv",
        "data/ir_sequence.xml",
    ],
    "images": ['static/description/icon.png'],
    "installable": True,
    "application": True,
    "auto_install": False,
}
